package envfile

import (
	"fmt"
	"strings"
)

// GenerateExample creates a .env.example from entries,
// stripping values and keeping keys with placeholder hints.
func GenerateExample(entries []Entry) string {
	var b strings.Builder
	b.WriteString("# Generated by kip generate\n")
	b.WriteString("# Fill in the values for your environment\n\n")

	for _, e := range entries {
		placeholder := inferPlaceholder(e.Key, e.Value)
		fmt.Fprintf(&b, "%s=%s\n", e.Key, placeholder)
	}

	return b.String()
}

// inferPlaceholder guesses a helpful placeholder based on the key name and value.
func inferPlaceholder(key, value string) string {
	lower := strings.ToLower(key)

	switch {
	case strings.Contains(lower, "port"):
		return "<port>"
	case strings.Contains(lower, "host"):
		return "<hostname>"
	case strings.Contains(lower, "url") || strings.Contains(lower, "uri"):
		return "<url>"
	case strings.Contains(lower, "password") || strings.Contains(lower, "passwd"):
		return "<password>"
	case strings.Contains(lower, "secret"):
		return "<secret>"
	case strings.Contains(lower, "key") || strings.Contains(lower, "token"):
		return "<key>"
	case strings.Contains(lower, "email"):
		return "<email>"
	case strings.Contains(lower, "name"):
		return "<name>"
	case strings.Contains(lower, "path") || strings.Contains(lower, "dir"):
		return "<path>"
	case isBooleanValue(value):
		return "<true|false>"
	case isNumericValue(value):
		return "<number>"
	default:
		return "<value>"
	}
}

func isBooleanValue(v string) bool {
	lower := strings.ToLower(v)
	return lower == "true" || lower == "false" || lower == "1" || lower == "0" || lower == "yes" || lower == "no"
}

func isNumericValue(v string) bool {
	if v == "" {
		return false
	}
	for _, c := range v {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}
